import { format, parseISO } from 'date-fns';

/**
 * Generates an iCalendar (.ics) string from the system bookings
 * This format is universally accepted by Google Calendar, Outlook, and Apple Calendar.
 */
export const generateICalFeed = (bookings) => {
  const header = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Vicinity IMS//Equipment Bookings//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:Vicinity Equipment Schedule',
    'X-WR-TIMEZONE:UTC'
  ];

  const events = bookings.map(booking => {
    // Format dates to YYYYMMDDTHHMMSSZ
    const start = booking.startDate.replace(/-/g, '') + 'T090000Z';
    const end = booking.endDate.replace(/-/g, '') + 'T180000Z';
    const stamp = format(new Date(), "yyyyMMdd'T'HHmmss'Z'");
    
    return [
      'BEGIN:VEVENT',
      `UID:${booking.id}@vicinity-ims.internal`,
      `DTSTAMP:${stamp}`,
      `DTSTART:${start}`,
      `DTEND:${end}`,
      `SUMMARY:[IMS] ${booking.equipmentName} - ${booking.shootName}`,
      `DESCRIPTION:Equipment: ${booking.equipmentName}\\nProject: ${booking.shootName}\\nUser: ${booking.user}\\nQuote: ${booking.quotationNumber || 'N/A'}\\n\\nGenerated by Vicinity IMS`,
      `LOCATION:Vicinity Studio / Client Site`,
      'END:VEVENT'
    ].join('\r\n');
  });

  const footer = ['END:VCALENDAR'];

  return [...header, ...events, ...footer].join('\r\n');
};

/**
 * Creates a downloadable blob for the .ics file
 */
export const downloadCalendarFeed = (bookings) => {
  const content = generateICalFeed(bookings);
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `vicinity-schedule-${format(new Date(), 'yyyy-MM-dd')}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};