<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use Carbon\Carbon;

class CalendarController extends Controller
{
    public function feed()
    {
        // Clear any previous output buffers to ensure clean ICS file
        if (ob_get_level()) {
            ob_end_clean();
        }

        $bookings = Booking::with(['user', 'equipments'])
            ->where('status', '!=', 'cancelled')
            ->whereNotNull('start_date')
            ->whereNotNull('end_date')
            ->get();

        // Get categories with their sort order outside the loop for efficiency
        $categories = \App\Models\Category::all()->pluck('sort_order', 'name')->toArray();

        $events = [];
        $now = gmdate('Ymd\THis\Z');

        foreach ($bookings as $booking) {
            // Ensure dates are valid
            if (! $booking->start_date || ! $booking->end_date) {
                continue;
            }

            try {
                $startDate = $booking->start_date instanceof Carbon ? $booking->start_date : Carbon::parse($booking->start_date);
                $endDate = $booking->end_date instanceof Carbon ? $booking->end_date : Carbon::parse($booking->end_date);
            } catch (\Exception $e) {
                continue;
            }

            // Format dates for iCal
            // All-day events in iCal use VALUE=DATE and the end date is EXCLUSIVE (end date + 1 day)
            // Syntax: DTSTART;VALUE=DATE:20260305
            $startDateStr = $startDate->format('Ymd');
            $endDateExclusiveStr = $endDate->copy()->addDay()->format('Ymd');

            $dtStartParam = 'VALUE=DATE:'.$startDateStr;
            $dtEndParam = 'VALUE=DATE:'.$endDateExclusiveStr;

            // Format equipment as a list grouped and sorted by category
            $equipmentGrouped = $booking->equipments->groupBy('category');
            
            $equipmentDisplay = "";
            $sortedCategories = $equipmentGrouped->keys()->sort(function($a, $b) use ($categories) {
                $orderA = $categories[$a] ?? 999;
                $orderB = $categories[$b] ?? 999;
                if ($orderA === $orderB) return strcmp($a, $b);
                return $orderA <=> $orderB;
            });

            foreach ($sortedCategories as $cat) {
                $items = $equipmentGrouped->get($cat)->sortBy('name');
                $equipmentDisplay .= "\n[" . strtoupper($cat) . "]\n";
                foreach ($items as $item) {
                    $qty = $item->pivot->quantity ?? 1;
                    $equipmentDisplay .= "- {$qty}x {$item->name}\n";
                }
            }

            if ($booking->equipments->isEmpty()) {
                $equipmentDisplay = 'None';
            }

            $userName = $booking->user ? $booking->user->name : 'Unknown User';
            $projectTitle = $booking->project_title ?? $booking->shoot_type ?? 'Untitled Project';
            $quotationNumber = $booking->quotation_number ?? 'N/A';
            
            // Format creation date for display (SGT is UTC+8)
            $createdDisplay = $booking->created_at 
                ? $booking->created_at->timezone('Asia/Singapore')->format('d M Y, h:ia') 
                : 'N/A';

            // Build Description
            // RFC 5545: Newlines in text must be escaped as \n or \N
            $descLines = [
                "Project: {$projectTitle}",
                "User: {$userName}",
                "Status: {$booking->status}",
                "Quote: {$quotationNumber}",
                "Booking Created: {$createdDisplay}",
                "Equipment: {$equipmentDisplay}",
                '',
                'Generated by Vicinity IMS',
            ];
            $description = implode("\n", $descLines); // Use real newlines
            $description = $this->escapeString($description, true); // Escape newlines to \n

            $summary = $this->escapeString("[IMS] {$projectTitle} - {$userName}");
            $location = $this->escapeString('Vicinity Studio');

            // Map Booking Status to ICS Status
            $icsStatus = 'CONFIRMED';
            if (in_array(strtolower($booking->status), ['pending', 'draft'])) {
                $icsStatus = 'TENTATIVE';
            } elseif (in_array(strtolower($booking->status), ['cancelled', 'rejected'])) {
                $icsStatus = 'CANCELLED';
            }

            // Build Event Lines (unfolded)
            $eventLines = [
                'BEGIN:VEVENT',
                'UID:'.$booking->id.'@ims.vicinity.sg',
                'DTSTAMP:'.$now,
                'DTSTART;'.$dtStartParam,
                'DTEND;'.$dtEndParam,
                'SUMMARY:'.$summary,
                'DESCRIPTION:'.$description,
                'LOCATION:'.$location,
                'STATUS:'.$icsStatus,
                'SEQUENCE:0',
                'TRANSP:OPAQUE',
                'END:VEVENT',
            ];

            // Fold lines and append to events
            foreach ($eventLines as $line) {
                $events[] = $this->foldLine($line);
            }
        }

        $icsHeader = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//Vicinity IMS//Equipment Schedule//EN',
            'CALSCALE:GREGORIAN',
            'METHOD:PUBLISH',
            'X-WR-CALNAME:Vicinity Equipment Schedule',
            'X-WR-TIMEZONE:UTC',
            'REFRESH-INTERVAL;VALUE=DURATION:PT5M',
            'X-PUBLISHED-TTL:PT5M',
        ];

        $icsFooter = [
            'END:VCALENDAR',
        ];

        // Combine all parts
        $outputLines = array_merge($icsHeader, $events, $icsFooter);
        $icsContent = implode("\r\n", $outputLines);

        return response($icsContent)
            ->header('Content-Type', 'text/calendar; charset=utf-8')
            ->header('Content-Disposition', 'attachment; filename="vicinity-schedule.ics"')
            ->header('Cache-Control', 'public, max-age=300');
    }

    /**
     * Escape special characters for ICS text values.
     *
     * @param  string  $string
     * @param  bool  $handleNewlines  Whether to convert real newlines to \n
     * @return string
     */
    private function escapeString($string, $handleNewlines = true)
    {
        // RFC 5545 requires escaping of: \ ; ,
        $string = str_replace('\\', '\\\\', $string);
        $string = str_replace(';', '\;', $string);
        $string = str_replace(',', '\,', $string);

        if ($handleNewlines) {
            $string = str_replace(["\r\n", "\r", "\n"], '\\n', $string);
        }

        return $string;
    }

    /**
     * Fold lines longer than 75 octets.
     *
     * @param  string  $line
     * @return string
     */
    private function foldLine($line)
    {
        if (strlen($line) <= 75) {
            return $line;
        }

        $folded = '';
        $first = true;

        while (strlen($line) > 0) {
            if ($first) {
                // First line limit is 75
                $chunk = substr($line, 0, 75);
                $line = substr($line, 75);
                $folded .= $chunk;
                $first = false;
            } else {
                // Subsequent lines limit is 74 (one space indent)
                $chunk = substr($line, 0, 74);
                $line = substr($line, 74);
                $folded .= "\r\n ".$chunk;
            }
        }

        return $folded;
    }
}
