<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use Illuminate\Http\Request;

class CalendarController extends Controller
{
    public function feed()
    {
        $bookings = Booking::with(['user', 'equipments'])
            ->where('status', '!=', 'cancelled')
            ->get();

        $events = [];
        $now = gmdate('Ymd\THis\Z');

        foreach ($bookings as $booking) {
            // Ensure dates are Carbon instances or valid date objects
            if (!$booking->start_date || !$booking->end_date) {
                continue;
            }

            $startDate = $booking->start_date->format('Ymd');
            $endDate = $booking->end_date->format('Ymd');
            
            // Default times: 09:00 to 18:00 UTC
            $dtStart = "{$startDate}T090000Z";
            $dtEnd = "{$endDate}T180000Z";
            
            $equipmentNames = $booking->equipments->pluck('name')->join(', ');
            $userName = $booking->user ? $booking->user->name : 'Unknown User';
            $projectTitle = $booking->project_title ?? $booking->shoot_type ?? 'Untitled Project';
            $quotationNumber = $booking->quotation_number ?? 'N/A';
            
            // Escape special characters in text fields (newline, semicolon, comma, backslash)
            // RFC 5545 requires escaping of: \ ; , and newlines
            $descriptionRaw = "Project: {$projectTitle}\nUser: {$userName}\nEquipment: {$equipmentNames}\nQuote: {$quotationNumber}\nStatus: {$booking->status}\n\nGenerated by Vicinity IMS";
            
            $description = $this->escapeString($descriptionRaw);
            $summary = $this->escapeString("[IMS] {$projectTitle} - {$userName}");
            $location = $this->escapeString("Vicinity Studio");

            $events[] = implode("\r\n", [
                'BEGIN:VEVENT',
                'UID:' . $booking->id . '@vicinity-ims',
                'DTSTAMP:' . $now,
                'DTSTART:' . $dtStart,
                'DTEND:' . $dtEnd,
                'SUMMARY:' . $summary,
                'DESCRIPTION:' . $description,
                'LOCATION:' . $location,
                'END:VEVENT'
            ]);
        }

        $icsHeader = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//Vicinity IMS//Equipment Schedule//EN',
            'CALSCALE:GREGORIAN',
            'METHOD:PUBLISH',
            'X-WR-CALNAME:Vicinity Equipment Schedule',
            'X-WR-TIMEZONE:UTC',
        ];

        $icsFooter = [
            'END:VCALENDAR'
        ];

        $icsContent = implode("\r\n", array_merge($icsHeader, $events, $icsFooter));

        return response($icsContent)
            ->header('Content-Type', 'text/calendar; charset=utf-8')
            ->header('Content-Disposition', 'inline; filename="vicinity-schedule.ics"')
            ->header('Cache-Control', 'no-cache, no-store, must-revalidate');
    }

    private function escapeString($string)
    {
        $string = str_replace('\\', '\\\\', $string);
        $string = str_replace(';', '\;', $string);
        $string = str_replace(',', '\,', $string);
        $string = str_replace("\n", '\\n', $string);
        return $string;
    }
}
